services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
     - MONGO_URI=mongodb://mongo:27017/tododb
    volumes:
      - ./todo-backend:/task
    depends_on:
      - mongo

  frontend:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./todo-frontend:/task
    depends_on:
      - backend

volumes:
  mongo-data:
